### ISSUE TITLE
errors with scoped dependencies

### ISSUE THREAD

**Issue by absurdist** [harish2704/npm-offline-registry#5]
hello

there seems to be an issue with scoped dependencies

the '/' is not being encoded in request

there has been a similar issue with sinopia

(https://github.com/rlidwka/sinopia/issues/399)

I've forked the code and fixed the issue with

https://github.com/absurdist/npm-offline-registry/commit/a856949e23a5de2b3a4c17f9cf9a4b7070b9da4c

//handle slash in scoped package name but do not convert @
packageName = encodeURIComponent(packageName).replace(/^%40/, '@');

I don't know your code so there might be a neater place for this

cheers

Mat

**Comment by absurdist** [comment]
Have fixed locally will fork and send pull request

**Comment by harish2704** [comment]
Thanks. Closing the issue since your pull request is already merged #6
